ZOOKEEPER=/homes/d/dadlanid/ece419/lab4/zookeeper
build:
	javac -classpath ${ZOOKEEPER}/zookeeper-3.3.2.jar:${ZOOKEEPER}/lib/log4j-1.2.15.jar ZkConnector.java \
	Packet.java \
	FileServerPacket.java \
	FileServer.java \
	FileServerHandlerThread.java \
	Worker.java \
	JobNode.java \
	Task.java \
	Serializer.java \
	ClientDriver.java \
	ClientPacket.java \
	JobTracker.java \
	JobTrackerHandlerThread.java

clean:
	rm -f *~ *.class
	
